name: Deploy to Hostinger (via FTP)

on:
  push:
    branches:
      - main  # Or the branch you're working on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to FTP server
        uses: schellman/ftp-deploy-action@v1
        with:
          server: 145.223.17.59
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./         # Local directory to upload
          remote-dir: /public_html/   # Remote directory on the server
          passive: true         # Enable Passive Mode
          timeout: 90           # Timeout (increase as needed)
