name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Or the branch you're working on

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up FTP deployment
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 145.223.17.59   # Replace with FTP server URL, stored as a secret
          username: ${{ secrets.FTP_USERNAME }}   # Replace with FTP username, stored as a secret
          password: ${{ secrets.FTP_PASSWORD }}   # Replace with FTP password, stored as a secret
          local-dir: ./  # Local directory to upload
          server-dir: /public_html/  # Remote directory on Hostinger
          port: 21  # FTP port (if using FTP)
          protocol: ftp  # Use 'ftp' for FTP, 'sftp' for SFTP (depending on your configuration)


