name: Deploy to Hostinger via FTP

on:
  push:
    branches:
      - main  # Or the branch you're working on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploy to FTP Server
        run: |
          lftp -e "set ftp:passive-mode true; set net:timeout 90; mirror -R ./ /public_html/; quit" -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}
